name: Build & Push Production Docker Containers

on:
    push:
        branches: main

env:
    DOCKERHUB_USERNAME: infiloop

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build and push Docker image
        id: build_core
        uses: docker/build-push-action@v6
        with:
          context: ./share/docker
          file: ./share/docker/prod/Dockerfile
          push: true
          target: core
          tags: infiloop/wfmeta_darshan:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push development Docker image
        id: build_dev
        uses: docker/build-push-action@v6
        with:
          context: ./share/docker
          file: ./share/docker/prod/Dockerfile
          push: true
          target: dev
          tags: infiloop/wfmeta_darshan_dev:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
